items:
  - label: Blog
    url: /blog.html
  - label: About
    children:
      - label: Contact
        url: /contact.html
      - label: About Me
        url: /about.html
  - label: Source
    url: https://github.com/joshchernoff/joshchernoff.github.io